repo_data = [
    {
        "name": "Sources Françaises",
        "pkg": "eu.kanade.tachiyomi.extension.fr.frenchsources",
        "apk": "frenchsources.apk",
        "lang": "fr",
        "code": 1,
        "version": "1.0.0",
        "nsfw": 0,
        "hasReadme": 0,
        "hasChangelog": 0,
        "sources": [
            {
                "name": "Mangas Origines",
                "lang": "fr",
                "id": 1849204817491,
                "baseUrl": "https://mangas-origines.fr"
            },
            {
                "name": "Sushi-Scan",
                "lang": "fr",
                "id": 2958102948192,
                "baseUrl": "https://sushiscan.net"
            },
            {
                "name": "Scan-Manga",
                "lang": "fr",
                "id": 7827492817491,
                "baseUrl": "https://www.scan-manga.com"
            }
        ]
    }
]
